apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiqinl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiqinl
  template:
    metadata:
      labels:
        app: aiqinl
    spec:
      containers:
      - image: okteto.dev/aiqinl:latest
        name: aiqinl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html"
        - name: Vless_UUID
          value: "1291e2a4-1c10-40b6-b9a3-990724bafbf5"
        - name: Vless_Path
          value: "/1291e2a4-1c10-40b6-b9a3-990724bafbf5-vless"
        - name: Vmess_UUID
          value: "1291e2a4-1c10-40b6-b9a3-990724bafbf5"
        - name: Vmess_Path
          value: "/1291e2a4-1c10-40b6-b9a3-990724bafbf5-vmess"
        - name: Share_Path
          value: "/vojqk"
